# Site settings
title: Heeyuen Koh
email: hy.koh@kist.re.kr
description: > # this means to ignore newlines until "baseurl:"
  Post doc working at KIST
  Interested in Neural network, nonlinear dynamics, multiscale simulation
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://heeyuen.com" # the base hostname & protocol for your site
twitter_username: ieebon
github_username:  ieebon
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
